[phases.setup]
nixPkgs = ["nodejs_22", "npm-9_x", "php82", "nginx", "libmysqlclient", "phpPackages.composer"]

[phases.install]
cmds = ["composer install --no-scripts --ignore-platform-reqs"]

[phases.build]
cmds = [
    "npm install",
    "php artisan wayfinder:generate --with-form || true",
    "npm run build:ssr || npm run build"
]